Feature/parquet encoder
bsm/feedx pull request #38
Opened 2021-08-26 11:21 UTC by jpmedforth

Very basic parquet writer. I just wanted to wrap `fraugster/parquet-go` as much as possible. Passing the schema in as an options is a bit faffy BUT i think it's the simplest way.  

As with reading the floor writer doesn't support int96.

2021-09-21 13:01 UTC, ajn approved these changes

2021-09-22 08:12 UTC, dim requested changes

2021-09-22 08:12 UTC, dim commented on ext/parquet/encoder.go
> +func (w encoder) Encode(v interface{}) error {
These should be pointer methods

2021-09-22 08:12 UTC, dim commented on ext/parquet/encoder.go
> +	fw *floor.Writer
you could just embed Writer and omit the Close method

2021-09-22 08:46 UTC, dim approved these changes

2021-09-22 09:14 UTC, merged